spring:
  datasource:
    url: jdbc:postgresql://fornecedor-db:5432/fornecedor
    username: postgres
    password: postgres
  flyway:
    schemas: fornecedor-migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        format_sql: true
        default_schema: fornecedor
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true

