spring:
  datasource:
    url: jdbc:postgresql://loja-db:5432/loja
    username: postgres
    password: postgres
  flyway:
    schemas: loja-migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: loja
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true

