spring:
  datasource:
    url: jdbc:postgresql://192.168.1.13:5434/loja
    username: postgres
    password: postgres
  flyway:
    schemas: loja-migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        format_sql: true
        default_schema: loja
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true

